// Mapping van landnamen naar landcodes
const countryCodeMapping = {
  "Canada": "CA",
  "Germany": "DE",
  "France": "FR",
  "Italy": "IT",
  "Japan": "JP",
  "United Kingdom": "GB",
  "United States": "US",
  "Argentina": "AR",
  "Afghanistan": "AF",
  "Australia": "AU",
  "Brazil": "BR",
  "China": "CN",
  "India": "IN",
  "Indonesia": "ID",
  "Mexico": "MX",
  "Russia": "RU",
  "Saudi Arabia": "SA",
  "South Korea": "KR",
  "Bahrain": "BH",
  "Bangladesh": "BD",
  "Angola": "AO",
  "Turkey": "TR",
  "Belgium": "BE",
  "Barbados": "BB",
  "Azerbijan": "AZ",
  "Bulgaria": "BG",
  "Andorra": "AD",
  "Belize": "BZ",
  "Belarus": "BY",
  "Cyprus": "CY",
  "Denmark": "DK",
  "Algeria": "DZ",
  "Estonia": "EE",
  "Finland": "FI",
  "Greece": "GR",
  "Hungary": "HU",
  "Ireland": "IE",
  "Croatia": "HR",
  "Latvia": "LV",
  "Lithuania": "LT",
  "Luxembourg": "LU",
  "Malta": "MT",
  "Netherlands": "NL",
  "Austria": "AT",
  "Poland": "PL",
  "Portugal": "PT",
  "Romania": "RO",
  "Slovenia": "SI",
  "Slovakia": "SK",
  "Spain": "ES",
  "Czech Republic": "CZ",
  "Sweden": "SE",
  "South Africa": "ZA",
  "Egypt": "EG",
  "Ethiopia": "ET",
  "Iran": "IR",
  "United Arab Emirates": "AE",
  "Albania": "AL",
  "Antigua and Barbuda": "AG",
  "Montenegro": "ME",
  "North Macedonia": "MK",
  "Namibia": "NA",
  "Morocco": "MA",
  "Ukraine": "UA",
  "Armenia": "AM",
  "Benin": "BJ",
  "Bhutan": "BT",
  "Bolivia": "BO",
  "Bosnia and Herzegovina": "BA",
  "Botswana": "BW",
  "Brunei": "BN",
  "Burkina Faso": "BF",
  "Burundi": "BI",
  "Cabo Verde": "CV",
  "Cambodia": "KH",
  "Cameroon": "CM",
  "Central African Republic": "CF",
  "Chad": "TD",
  "Chile": "CL",
  "Colombia": "CO",
  "Comoros": "KM",
  "Congo (Democratic Republic)": "CD",
  "Congo (Republic)": "CG",
  "Costa Rica": "CR",
  "Cuba": "CU",
  "Djibouti": "DJ",
  "Dominica": "DM",
  "Dominican Republic": "DO",
  "Ecuador": "EC",
  "El Salvador": "SV",
  "Equatorial Guinea": "GQ",
  "Eritrea": "ER",
  "Eswatini": "SZ",
  "Fiji": "FJ",
  "Gabon": "GA",
  "Gambia": "GM",
  "Georgia": "GE",
  "Ghana": "GH",
  "Grenada": "GD",
  "Guatemala": "GT",
  "Guinea": "GN",
  "Guinea-Bissau": "GW",
  "Guyana": "GY",
  "Haiti": "HT",
  "Honduras": "HN",
  "Iceland": "IS",
  "Jamaica": "JM",
  "Jordan": "JO",
  "Kazakhstan": "KZ",
  "Kenya": "KE",
  "Kiribati": "KI",
  "Kuwait": "KW",
  "Kyrgyzstan": "KG",
  "Laos": "LA",
  "Lebanon": "LB",
  "Lesotho": "LS",
  'Bahamas': "BS",
  "Liberia": "LR",
  "Libya": "LY",
  "Liechtenstein": "LI",
  "Madagascar": "MG",
  "Malawi": "MW",
  "Malaysia": "MY",
  "Maldives": "MV",
  "Mali": "ML",
  "Marshall Islands": "MH",
  "Mauritania": "MR",
  "Mauritius": "MU",
  "Micronesia": "FM",
  "Moldova": "MD",
  "Monaco": "MC",
  "Mongolia": "MN",
  "Mozambique": "MZ",
  "Myanmar": "MM",
  "Nauru": "NR",
  "Nepal": "NP",
  "Nicaragua": "NI",
  "Niger": "NE",
  "Nigeria": "NG",
  "Oman": "OM",
  "Pakistan": "PK",
  "Palau": "PW",
  "Panama": "PA",
  "Papua New Guinea": "PG",
  "Paraguay": "PY",
  "Peru": "PE",
  "Philippines": "PH",
  "Qatar": "QA",
  "Rwanda": "RW",
  "Saint Kitts and Nevis": "KN",
  "Saint Lucia": "LC",
  "Saint Vincent and the Grenadines": "VC",
  "Samoa": "WS",
  "San Marino": "SM",
  "Sao Tome and Principe": "ST",
  "Senegal": "SN",
  "Serbia": "RS",
  "Seychelles": "SC",
  "Sierra Leone": "SL",
  "Singapore": "SG",
  "Solomon Islands": "SB",
  "Somalia": "SO",
  "Sri Lanka": "LK",
  "Sudan": "SD",
  "Suriname": "SR",
  "Syria": "SY",
  "Tajikistan": "TJ",
  "Tanzania": "TZ",
  "Thailand": "TH",
  "Timor-Leste": "TL",
  "Togo": "TG",
  "Tonga": "TO",
  "Trinidad and Tobago": "TT",
  "Tunisia": "TN",
  "Turkmenistan": "TM",
  "Tuvalu": "TV",
  "Uganda": "UG",
  "Uruguay": "UY",
  "Uzbekistan": "UZ",
  "Vanuatu": "VU",
  "Vatican City": "VA",
  "Venezuela": "VE",
  "Vietnam": "VN",
  "Yemen": "YE",
  "Zambia": "ZM",
  "Zimbabwe": "ZW"
};


// Landen met stoel en groepen
export const countries = [
  { name: "Canada", seat: 1, groups: ["all", "g7", "nato"] },
  { name: "Germany", seat: 2, groups: ["all", "g7", "european union",   "nato"] },
  { name: "France", seat: 3, groups: ["all", "g7", "european union", "securitycouncil", "nato"] },
  { name: "Italy", seat: 4, groups: ["all", "g7", "european union",   "nato"] },
  { name: "Japan", seat: 5, groups: ["all", "g7", "g20"] },
  { name: "United Kingdom", seat: 6, groups: ["all", "g7", "securitycouncil",   "nato"] },
  { name: "United States", seat: 7, groups: ["all", "g7",   "securitycouncil", "nato"] },
  { name: "Argentina", seat: 8, groups: ["all",   "brics"] },
  { name: "Australia", seat: 9, groups: ["all", "g20"] },
  { name: "Brazil", seat: 10, groups: ["all", "brics"] },
  { name: "China", seat: 11, groups: ["all", "securitycouncil", "brics"] },
  { name: "India", seat: 12, groups: ["all", "brics"] },
  { name: "Indonesia", seat: 13, groups: ["all", "g20"] },
  { name: "Mexico", seat: 14, groups: ["all", "brics"] },
  { name: "Russia", seat: 15, groups: ["all",  "securitycouncil", "brics"] },
  { name: "Saudi Arabia", seat: 16, groups: ["all","brics"] },
  { name: "South Korea", seat: 17, groups: ["all", "g20"] },
  { name: "Turkey", seat: 18, groups: ["all",   "nato"] },
  { name: "Belgium", seat: 19, groups: ["all", "european union", "nato"] },
  { name: "Bulgaria", seat: 20, groups: ["all", "european union", "nato"] },
  { name: "Cyprus", seat: 21, groups: ["all", "european union"] },
  { name: "Denmark", seat: 22, groups: ["all", "european union", "nato"] },
  { name: "Estonia", seat: 23, groups: ["all", "european union", "nato"] },
  { name: "Finland", seat: 24, groups: ["all", "european union", "nato"] },
  { name: "Greece", seat: 25, groups: ["all", "european union", "nato"] },
  { name: "Hungary", seat: 26, groups: ["all", "european union", "nato"] },
  { name: "Ireland", seat: 27, groups: ["all", "european union"] },
  { name: "Croatia", seat: 28, groups: ["all", "european union","nato"] },
  { name: "Latvia", seat: 29, groups: ["all","european union", "nato"] },
  { name: "Lithuania", seat: 30, groups: ["all", "european union",  "nato"] },
  { name: "Luxembourg", seat: 31, groups: ["all", "european union", "nato"] },
  { name: "Malta", seat: 32, groups: ["all", "european union"] },
  { name: "Netherlands", seat: 33, groups: ["all", "european union", "nato"] },
  { name: "Austria", seat: 34, groups: ["all", "european union"] },
  { name: "Poland", seat: 35, groups: ["all", "nato", "european union"] },
  { name: "Portugal", seat: 36, groups: ["all", "nato", "european union"] },
  { name: "Romania", seat: 37, groups: ["all", "european union", "nato"] },
  { name: "Slovenia", seat: 38, groups: ["all", "european union", "nato"] },
  { name: "Slovakia", seat: 39, groups: ["all", "european union", "nato"] },
  { name: "Spain", seat: 40, groups: ["all", "european union", "nato"] },
  { name: "Czech Republic", seat: 41, groups: ["all", "european union", "nato"] },
  { name: "Sweden", seat: 42, groups: ["all", "european union"] },
  { name: "South Africa", seat: 43, groups: ["all",   "brics"] },
  { name: "Egypt", seat: 44, groups: ["all", "brics"] },
  { name: "Ethiopia", seat: 45, groups: ["all", "brics"] },
  { name: "Iran", seat: 46, groups: ["all", "brics"] },
  { name: "United Arab Emirates", seat: 47, groups: ["all", "brics"] },
  { name: "Albania", seat: 48, groups: ["all", "nato"] },
  { name: "Montenegro", seat: 49, groups: ["all", "nato"] },
  { name: "North Macedonia", seat: 50, groups: ["all", "nato"] },
  { name: "Namibia", seat: 51, groups: ["all", "nato"] },
  { name: "Morocco", seat: 52, groups: ["all", "nato"] },
  { name: "Ukraine", seat: 53, groups: ["all", "nato"] },
  { name: "Afghanistan", seat: 54, groups: ["all", "nato"] },
  { name: "Algeria", seat: 55, groups: ["all", "nato"] },
  { name: "Andorra", seat: 56, groups: ["all", "nato"] },
  { name: "Angola", seat: 57, groups: ["all", "nato"] },
  { name: "Antigua and Barbuda", seat: 58, groups: ["all", "nato"] },
  { name: "Armenia", seat: 59, groups: ["all", "nato"] },
  { name: "Azerbijan", seat: 60, groups: ["all", "nato"] },
  { name: "Bahamas", seat: 61, groups: ["all"] },
{ name: "Bahrain", seat: 62, groups: ["all"] },
{ name: "Bangladesh", seat: 63, groups: ["all"] },
{ name: "Barbados", seat: 64, groups: ["all"] },
{ name: "Belarus", seat: 65, groups: ["all"] },
{ name: "Belize", seat: 66, groups: ["all"] },
{ name: "Benin", seat: 67, groups: ["all"] },
{ name: "Bhutan", seat: 68, groups: ["all"] },
{ name: "Bolivia", seat: 69, groups: ["all"] },
{ name: "Bosnia and Herzegovina", seat: 70, groups: ["all"] },
{ name: "Botswana", seat: 71, groups: ["all"] },
{ name: "Brunei", seat: 72, groups: ["all"] },
{ name: "Burkina Faso", seat: 73, groups: ["all"] },
{ name: "Burundi", seat: 74, groups: ["all"] },
{ name: "Cabo Verde", seat: 75, groups: ["all"] },
{ name: "Cambodia", seat: 76, groups: ["all"] },
{ name: "Cameroon", seat: 77, groups: ["all"] },
{ name: "Central African Republic", seat: 78, groups: ["all"] },
{ name: "Chad", seat: 79, groups: ["all"] },
{ name: "Chile", seat: 80, groups: ["all", "g20"] },
{ name: "Colombia", seat: 81, groups: ["all"] },
{ name: "Comoros", seat: 82, groups: ["all"] },
{ name: "Congo (Democratic Republic)", seat: 83, groups: ["all"] },
{ name: "Congo (Republic)", seat: 84, groups: ["all"] },
{ name: "Costa Rica", seat: 85, groups: ["all"] },
{ name: "Cuba", seat: 86, groups: ["all"] },
{ name: "Djibouti", seat: 87, groups: ["all"] },
{ name: "Dominica", seat: 88, groups: ["all"] },
{ name: "Dominican Republic", seat: 89, groups: ["all"] },
{ name: "Ecuador", seat: 90, groups: ["all"] },
{ name: "El Salvador", seat: 91, groups: ["all"] },
{ name: "Equatorial Guinea", seat: 92, groups: ["all"] },
{ name: "Eritrea", seat: 93, groups: ["all"] },
{ name: "Eswatini", seat: 94, groups: ["all"] },
{ name: "Fiji", seat: 95, groups: ["all"] },
{ name: "Gabon", seat: 96, groups: ["all"] },
{ name: "Gambia", seat: 97, groups: ["all"] },
{ name: "Georgia", seat: 98, groups: ["all"] },
{ name: "Ghana", seat: 99, groups: ["all"] },
{ name: "Grenada", seat: 100, groups: ["all"] },
{ name: "Guatemala", seat: 101, groups: ["all"] },
{ name: "Guinea", seat: 102, groups: ["all"] },
{ name: "Guinea-Bissau", seat: 103, groups: ["all"] },
{ name: "Guyana", seat: 104, groups: ["all"] },
{ name: "Haiti", seat: 105, groups: ["all"] },
{ name: "Honduras", seat: 106, groups: ["all"] },
{ name: "Iceland", seat: 107, groups: ["all", "nato"] },
{ name: "Jamaica", seat: 108, groups: ["all"] },
{ name: "Jordan", seat: 109, groups: ["all"] },
{ name: "Kazakhstan", seat: 110, groups: ["all"] },
{ name: "Kenya", seat: 111, groups: ["all"] },
{ name: "Kiribati", seat: 112, groups: ["all"] },
{ name: "Kuwait", seat: 113, groups: ["all"] },
{ name: "Kyrgyzstan", seat: 114, groups: ["all"] },
{ name: "Laos", seat: 115, groups: ["all"] },
{ name: "Lebanon", seat: 116, groups: ["all"] },
{ name: "Lesotho", seat: 117, groups: ["all"] },
{ name: "Liberia", seat: 118, groups: ["all"] },
{ name: "Libya", seat: 119, groups: ["all"] },
{ name: "Liechtenstein", seat: 120, groups: ["all"] },
{ name: "Madagascar", seat: 121, groups: ["all"] },
{ name: "Malawi", seat: 122, groups: ["all"] },
{ name: "Malaysia", seat: 123, groups: ["all"] },
{ name: "Maldives", seat: 124, groups: ["all"] },
{ name: "Mali", seat: 125, groups: ["all"] },
{ name: "Marshall Islands", seat: 126, groups: ["all"] },
{ name: "Mauritania", seat: 127, groups: ["all"] },
{ name: "Mauritius", seat: 128, groups: ["all"] },
{ name: "Micronesia", seat: 129, groups: ["all"] },
{ name: "Moldova", seat: 130, groups: ["all"] },
{ name: "Monaco", seat: 131, groups: ["all"] },
{ name: "Mongolia", seat: 132, groups: ["all"] },
{ name: "Mozambique", seat: 133, groups: ["all"] },
{ name: "Myanmar", seat: 134, groups: ["all"] },
{ name: "Nauru", seat: 135, groups: ["all"] },
{ name: "Nepal", seat: 136, groups: ["all"] },
{ name: "Nicaragua", seat: 137, groups: ["all"] },
{ name: "Niger", seat: 138, groups: ["all"] },
{ name: "Nigeria", seat: 139, groups: ["all"] },
{ name: "Oman", seat: 140, groups: ["all"] },
{ name: "Pakistan", seat: 141, groups: ["all"] },
{ name: "Palau", seat: 142, groups: ["all"] },
{ name: "Panama", seat: 143, groups: ["all"] },
{ name: "Papua New Guinea", seat: 144, groups: ["all"] },
{ name: "Paraguay", seat: 145, groups: ["all"] },
{ name: "Peru", seat: 146, groups: ["all"] },
{ name: "Philippines", seat: 147, groups: ["all"] },
{ name: "Qatar", seat: 148, groups: ["all"] },
{ name: "Rwanda", seat: 149, groups: ["all"] },
{ name: "Saint Kitts and Nevis", seat: 150, groups: ["all"] },
{ name: "Saint Lucia", seat: 151, groups: ["all"] },
{ name: "Saint Vincent and the Grenadines", seat: 152, groups: ["all"] },
{ name: "Samoa", seat: 153, groups: ["all"] },
{ name: "San Marino", seat: 154, groups: ["all"] },
{ name: "Sao Tome and Principe", seat: 155, groups: ["all"] },
{ name: "Senegal", seat: 156, groups: ["all"] },
{ name: "Serbia", seat: 157, groups: ["all"] },
{ name: "Seychelles", seat: 158, groups: ["all"] },
{ name: "Sierra Leone", seat: 159, groups: ["all"] },
{ name: "Singapore", seat: 160, groups: ["all"] },
{ name: "Solomon Islands", seat: 161, groups: ["all"] },
{ name: "Somalia", seat: 162, groups: ["all"] },
{ name: "Sri Lanka", seat: 163, groups: ["all"] },
{ name: "Sudan", seat: 164, groups: ["all"] },
{ name: "Suriname", seat: 165, groups: ["all"] },
{ name: "Syria", seat: 166, groups: ["all"] },
{ name: "Tajikistan", seat: 167, groups: ["all"] },
{ name: "Tanzania", seat: 168, groups: ["all"] },
{ name: "Thailand", seat: 169, groups: ["all"] },
{ name: "Timor-Leste", seat: 170, groups: ["all"] },
{ name: "Togo", seat: 171, groups: ["all"] },
{ name: "Tonga", seat: 172, groups: ["all"] },
{ name: "Trinidad and Tobago", seat: 173, groups: ["all"] },
{ name: "Tunisia", seat: 174, groups: ["all"] },
{ name: "Turkmenistan", seat: 175, groups: ["all"] },
{ name: "Tuvalu", seat: 176, groups: ["all"] },
{ name: "Uganda", seat: 177, groups: ["all"] },
{ name: "Uruguay", seat: 178, groups: ["all"] },
{ name: "Uzbekistan", seat: 179, groups: ["all"] },
{ name: "Vanuatu", seat: 180, groups: ["all"] },
{ name: "Vatican City", seat: 181, groups: ["all"] },
{ name: "Venezuela", seat: 182, groups: ["all"] },
{ name: "Vietnam", seat: 183, groups: ["all"] },
{ name: "Yemen", seat: 184, groups: ["all"] },
{ name: "Zambia", seat: 185, groups: ["all"] },
{ name: "Zimbabwe", seat: 186, groups: ["all"] },
{ name: "Marshall Islands", seat: 187, groups: ["all"] },
{ name: "Nauru", seat: 188, groups: ["all"] },
{ name: "Saint Vincent and the Grenadines", seat: 189, groups: ["all"] },
{ name: "Palau", seat: 190, groups: ["all"] },
{ name: "Solomon Islands", seat: 191, groups: ["all"] },
{ name: "Samoa", seat: 192, groups: ["all"] },
{ name: "Vanuatu", seat: 193, groups: ["all"] }
];


// Functie om landen te filteren op groep
export function getCountriesByGroup(group) {
  return countries.filter(country => country.groups.includes(group));
}

// Functie om vlag-URL op te halen
export function getFlagUrl(countryName) {
  const flagBaseUrl = "https://flagsapi.com/";
  const countryCode = countryCodeMapping[countryName];  
  return countryCode ? `${flagBaseUrl}${countryCode}/flat/64.png` : '';  // Retourneer de juiste URL of een lege string
}